spring:
  profiles:
    active:  dev

--

spring:
  profiles: dev
    application:
      name: springc;oud-config-dev


--


spring:
  profiles: test
    application:
      name: springc;oud-config-test
